import forms from '@tailwindcss/forms'

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-error': '#ffffff',
        'tertiary-container': '#3d455a',
        'on-tertiary-container': '#abb2cc',
        'inverse-on-surface': '#eff1f3',
        primary: '#002b6b',
        'on-tertiary-fixed-variant': '#3f465c',
        'surface-container-high': '#e6e8ea',
        'tertiary-fixed-dim': '#bec6e0',
        'on-tertiary': '#ffffff',
        'on-surface': '#191c1e',
        'on-primary-container': '#91b1ff',
        'surface-dim': '#d8dadc',
        'primary-fixed-dim': '#b0c6ff',
        'inverse-surface': '#2d3133',
        'surface-container': '#eceef0',
        'on-secondary-fixed': '#0d1c2e',
        'surface-variant': '#e0e3e5',
        'secondary-fixed': '#d5e3fc',
        'on-surface-variant': '#434651',
        'primary-container': '#1a428a',
        'on-background': '#191c1e',
        'surface-container-highest': '#e0e3e5',
        'on-primary-fixed-variant': '#1c448c',
        'on-error-container': '#93000a',
        'on-primary-fixed': '#001944',
        error: '#ba1a1a',
        background: '#f7f9fb',
        'surface-container-low': '#f2f4f6',
        surface: '#f7f9fb',
        'secondary-fixed-dim': '#b9c7df',
        outline: '#747782',
        secondary: '#515f74',
        'surface-container-lowest': '#ffffff',
        'primary-fixed': '#d9e2ff',
        'surface-bright': '#f7f9fb',
        'on-secondary': '#ffffff',
        'on-tertiary-fixed': '#131b2e',
        tertiary: '#272f43',
        'on-secondary-container': '#57657a',
        'on-secondary-fixed-variant': '#3a485b',
        'secondary-container': '#d5e3fc',
        'inverse-primary': '#b0c6ff',
        'surface-tint': '#395ca5',
        'error-container': '#ffdad6',
        'outline-variant': '#c4c6d2',
        'tertiary-fixed': '#dae2fd',
        'on-primary': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Manrope', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [forms],
}
